/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "primos.h"

int *
contar_1_svc(int nip, int min, int max,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct primos *
buscar_1_svc(int nip, int min, int max,  struct svc_req *rqstp)
{
	static struct primos  result;

	/*
	 * insert server code here
	 */

	return &result;
}
