/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "primos.h"

bool_t
xdr_primos (XDR *xdrs, primos *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, (1 +  5761456 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->numero))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->vector, 5761456,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->numero);
			{
				register int *genp;

				for (i = 0, genp = objp->vector;
					i < 5761456; ++i) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, (1 +  5761456 )* BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->numero))
				 return FALSE;
			 if (!xdr_vector (xdrs, (char *)objp->vector, 5761456,
				sizeof (int), (xdrproc_t) xdr_int))
				 return FALSE;
		} else {
			objp->numero = IXDR_GET_LONG(buf);
			{
				register int *genp;

				for (i = 0, genp = objp->vector;
					i < 5761456; ++i) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->numero))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->vector, 5761456,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_contar_1_argument (XDR *xdrs, contar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->nip))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_buscar_1_argument (XDR *xdrs, buscar_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->nip))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->min))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->max))
		 return FALSE;
	return TRUE;
}
