/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calcular_primos.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_contar_1 (contar_1_argument *argp, struct svc_req *rqstp)
{
	return (contar_1_svc(argp->nip, argp->min, argp->max, rqstp));
}

static struct encontrados *
_buscar_1 (buscar_1_argument *argp, struct svc_req *rqstp)
{
	return (buscar_1_svc(argp->nip, argp->min, argp->max, rqstp));
}

static void
primos_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		contar_1_argument contar_1_arg;
		buscar_1_argument buscar_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case contar:
		_xdr_argument = (xdrproc_t) xdr_contar_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _contar_1;
		break;

	case buscar:
		_xdr_argument = (xdrproc_t) xdr_buscar_1_argument;
		_xdr_result = (xdrproc_t) xdr_encontrados;
		local = (char *(*)(char *, struct svc_req *)) _buscar_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (PRIMOS, UNO);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, PRIMOS, UNO, primos_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (PRIMOS, UNO, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, PRIMOS, UNO, primos_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (PRIMOS, UNO, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
